### ISSUE TITLE
Real Time Heart Rate Data

### ISSUE THREAD

**Issue by aytunch** [Spayker/rn-miband-connector#4]
Hi @Spayker Thanks for this great project. I would like to first know if this library supports real time continuous heart monitoring or is it getting one-time heart rate data over and over again over an interval? 

If you could summarize the steps required for **real time heart monitoring** I would be very glad. The way I understand from your code now is as follows. Please correct me if I am wrong:
**1-** Connect to Device(Ok)
**2-** Authorize Device(works perfectly and I understand the process well)
**3-** Subscribe to CHAR_HEART_RATE_CONTROL notifications **(however seems like there is no notify property for CHAR_HEART_RATE_CONTROL)**
**4-** Subscribe to CHAR_HEART_RATE_MEASURE notifications
**5-** Write a [1, 3, 19] to the `CHAR_SENSOR` Control Characteristic **(when I check the `CHAR_SENSOR` control properties, it seems that write is not allowed. Should we do something else in order to be able to write? Am i missing a step?)**
**6-** Get back [1, 3, 25] from `CHAR_SENSOR` control character notification **(how are we getting a notification from `CHAR_SENSOR` since we never subscribed to its notify service in `onCharacteristicWrite`??)**
**7-** write `ENABLE_NOTIFICATION_VALUE`:[1, 0] to the descriptor of `CHAR_HEART_RATE_MEASURE`(hrDescChar)
**8-** get back [1, 0] from `CHAR_HEART_RATE_MEASURE` descriptor notification
**9-** Write [15, 1, 1] to `CHAR_HEART_RATE_CONTROL` for starting continuous heart rate measurement.
**10-** get back the current heart rate value from `CHAR_HEART_RATE_MEASURE` inside `onCharacteristicChanged`
**11-** write [16] to CHAR_HEART_RATE_CONTROL every 5000ms to keep on getting values?

Either the steps I follow are unordered or I am missing something while reading the code:/

I looked at the code and it seems these are the relevant codes to the subject:

```
private void startHrCalculation(Callback successCallback) {
        sensorChar.setValue(new byte[]{0x01, 0x03, 0x19});
        btGatt.writeCharacteristic(sensorChar);
        successCallback.invoke(null, heartRateValue);
    }
```

```
private void getHeartRate(String currentHeartBeat, Callback successCallback) {
        if(Integer.valueOf(heartRateValue).equals(Integer.valueOf(currentHeartBeat))){
            hrCtrlChar.setValue(new byte[]{0x16});
            btGatt.writeCharacteristic(hrCtrlChar);
        }
        successCallback.invoke(null, heartRateValue);
    }
```

In the below code if I understood right, even if we send a [1, 3, 19] to the CHAR_SENSOR, we should expect to get a response starting with [1, 3, 25]
```
BluetoothGattCharacteristic hrMeasureChar = heartService.getCharacteristic(UUID.fromString(CHAR_HEART_RATE_MEASURE));
hrDescChar = hrMeasureChar.getDescriptor(UUID.fromString(NOTIFICATION_DESC));

public void onCharacteristicWrite(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, int status){
        switch (characteristic.getUuid().toString()) {
            case CHAR_SENSOR: {
                switch (Arrays.toString(characteristic.getValue())){
                    // for real time HR measurement [1, 3, 19] was sent actually but [1, 3, 25]
                    // is written. Magic?
                    case "[1, 3, 25]":{
                        hrDescChar.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
                        gatt.writeDescriptor(hrDescChar);
                    }
                }
            }
        }
    }
```

```
public void onDescriptorWrite(BluetoothGatt gatt, BluetoothGattDescriptor descriptor, int status) {
        switch (descriptor.getCharacteristic().getUuid().toString()){
            case CHAR_HEART_RATE_MEASURE:{
                switch (Arrays.toString(descriptor.getValue())){
                    case "[1, 0]":{
                        hrCtrlChar.setValue(new byte[]{0x15, 0x01, 0x01});
                        Log.d("INFO","hrCtrlChar: " + gatt.writeCharacteristic(hrCtrlChar));
                    }
                }
            }
        }
    }
```

This part made me unsure about if heart rate measurement was made continuously or just one time measurement in an infinite loop with 5000ms intervals.
```
activateHeartRateCalculation = () => {
        NativeModules.HeartBeatMeasurer.startHrCalculation((error, heartBeatRate) => {
            this.setState({ isHeartRateCalculating: true})
            this.setState({ heartBeatRate: heartBeatRate})
        })
        this.setState({ hrRateInterval: setInterval(this.getHeartRate, 5000)})
    }

getHeartRate = () => {
        NativeModules.HeartBeatMeasurer.getHeartRate( this.state.heartBeatRate, (error, heartBeatRate) => {
            this.setState({ heartBeatRate: heartBeatRate})
        })
    }
```

In your article: [MiBand 3 and React Native (Part One)](https://dzone.com/articles/miband-3-and-react-native-partnbsp1) you talk about:

> makePause() smells like a workaround. Still I am looking for a proper way when the module won't make pauses in communication with a device but will wait for some certain response and perform next steps.

However, I can not see any `makePause()` in the code. Is the Github code renewed version of the article? especially the `HeartBeatMeasurer.java` is very different than the article. And is part 2 of the article out? **EDIT:** I just found about the stale mk2 branch and saw the changes.

Finally, may I ask how you managed to find out the required steps to connect to MiBand3? Its outstanding work. I tried by using wireshark and couldn't do it:)

Too many questions, I know but I really liked your work, and I am trying to teach my self about Bluetooth and devices and software and this seems like a perfect project.

**Comment by Spayker** [comment]
Hi @aytunch 

Thanks for kind words. As you know I prepared 2 articles recently. I strongly recommend to check [second part](https://dzone.com/articles/miband-3-and-react-native-part-two) since it contains major part of answers  on your questions.

However, just in case I am leaving answers below: 
> is it getting one-time heart rate data over and over again over an interval?

It gets heart rate in real time. It's possible because of periodical request to peripheral device. It asks to start a heart rate measurement again and again till you press stop measurement. Period to re-ask is set to 5 seconds. Check "**activateHeartRateCalculation**" function in **Dashboard.jsx**

If you check Android native implementation of heart measurement you will find next sequence:
1) set value to sensor char: sensorChar.setValue(new byte[]{0x01, 0x03, 0x19});
2) write sensor char: btGatt.writeCharacteristic(sensorChar);
3) handle char write event in "onCharacteristicWrite" method and set  ENABLE value to HR descriptor:
`
switch (characteristic.getUuid().toString()) {
            case CHAR_SENSOR: {
                switch (Arrays.toString(characteristic.getValue())){
                    case "[1, 3, 25]":{
                        hrDescChar.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);
                        gatt.writeDescriptor(hrDescChar);
                    }
                }
            }
            default:
                Log.d("INFO", "onCharacteristicWrite uuid: " + characteristic.getUuid().toString()
                        + " value: " + Arrays.toString(characteristic.getValue()) + " status: " + status);
}
`
4) Finally you need to intercept reply from peripheral device. You can do it in "onCharacteristicChanged" method:
`
switch (characteristic.getUuid().toString()){
            // ...
            case CHAR_HEART_RATE_MEASURE:{
                heartBeatMeasurer.handleHeartRateData(characteristic);
                break;
            }
}
`

Like I said previously, please check second chapter. You will find there lot of valuable info. If you have some questions remained unanswered please ask here.

**Comment by aytunch** [comment]
Thank you very much, I will try to test again with this knowledge. About the second part of the article, I just found about it from the youtube video: [Xiaomi MiBand 3 and React-Native. Testing of Android part.](https://www.youtube.com/watch?v=Jwz9kGWV8ZQ&lc=z23afbkz5rapi11yi04t1aokgqezenomm4gkfnmvhjywrk0h00410.1572894320779797). I think it would be better to update article part1 with part2's link:) Part2 of this awesome article explains real time heart rate in much depth but still I am having some difficulty. 

Before I go on and try to implement some code according to the info here, can I ask a clarification:
what is the difference between these three:
`onCharacteristicRead`
`onCharacteristicWrite`
`onCharacteristicChanged`

I know we can read, write and get notifications from a Bluetooth Characteristic. But I always thought we only listen to the notify channel of the characteristic. And after we write something, the MiBand3 responds through the notify channel of the corresponding characteristic. 

So why do we listen to 3 different onCharacteristicRead, onCharacteristicWrite, onCharacteristicChanged channels? In what circumstances do each of them fire up? 

inside of `public void updateHrChars(BluetoothGatt gatt)`
```
btGatt.setCharacteristicNotification(hrCtrlChar, true);
btGatt.setCharacteristicNotification(hrMeasureChar, true);
```
we subscribe to these 2 character notifications. Other than these two and one for auth, I can not see any other `setCharacteristicNotification`. So no subscription to `CHAR_SENSOR` notification at all right? That's a big confusion for me.

**Comment by Spayker** [comment]
> I think it would be better to update article part1 with part2's link:)

Yeah, going to update it asap :)

Those three mentioned methods are part of **BluetoothGattCallback** class. It's responsible for data transfer management between a mobile app and peripheral devices. 
**onCharacteristicRead** - Callback reporting the result of a characteristic read operation.
**onCharacteristicWrite** - Callback indicating the result of a characteristic write operation. 
**onCharacteristicChanged** - Callback triggered as a result of a remote characteristic notification.

In general they work like listeners, f.e.: if a write data event has just happened (some data has been written to device), **onCharacteristicWrite** method will be invoked. Same principle for read and changed methods. 

My investigations point on one important thing:
methods help to control communication process by intercepting appropriate events we can have    during read/write device operations. It uses an event driven approach: when you have just registered some read/write event and must act in an appropriate way. Answering your question regarding "makePause()" method: I do not need this method anymore since event management resolves my problem with possible latency: when a peripheral device requires some time to process received request, prepare a reply and send it back. By selected approach I am just waiting for that reply from device and do not set time limits, specified in method.

Sensor characteristic does not require any subscription. At least my tests say so :) . HR control  point (2a39) and HR measure (2a37) are characteristics of one HR service (180d). Since you are expecting to get some data from them you must enable notification mode for them.
